1/codeblock/urls.py
from django.conf.urls import patterns, include, url
from press.views import HomeView,TagView,CategoryView,ArticleView,ArchiveView
from feeds.feeds import LatestPress
from press.models import Press
from django.views.generic.dates import ArchiveIndexView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
admin.autodiscover()

archive_dict = {
                'queryset':Press.objects.all(),
                'date_field':'date_pub',
                }

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'codeblock.views.home', name='home'),
    # url(r'^codeblock/', include('codeblock.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^$',HomeView),
    (r'^tag/(\d*)/$',TagView),
    (r'^category/$',CategoryView),
    url(r'^(\d*)/$',ArticleView,name="article"),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'feed/$',LatestPress()),
    url(r'^archive/$',
        ArchiveIndexView.as_view(model=Press, date_field="date_pub"),
        name="article_archive"),
)

            
urlpatterns += staticfiles_urlpatterns()

1/gravatar/models.py
from django.db import models

# Create your models here.

1/my_comment_app/models.py
from django.db import models
from django import forms
from django.contrib.comments.models import Comment
# Create your models here.

class CommentWithReply(Comment):
    rName = models.CharField("rName",max_length=20)
    rContent = models.TextField("rContent")

1/press/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    cname = models.CharField(max_length=10)
    
    def __unicode__(self):
        return self.cname

class Tag(models.Model):
    tname = models.CharField(max_length=20)
    
    def __unicode__(self):
        return self.tname

class Press(models.Model):
    title = models.CharField(max_length=50)
    title_en = models.CharField(max_length=100)
    cover = models.CharField(max_length=200)
    date_pub = models.DateTimeField(auto_now=True)
    page_view = models.IntegerField(default=0)
    introduce = models.TextField()
    content = models.TextField()
    
    tags = models.ManyToManyField(Tag)
    category = models.ForeignKey(Category)
    
    def __unicode__(self):
        return self.title
    class Meta:
        ordering = ["-date_pub"]

# class CommentWithReply(models.Model):

1/my_comment_app/forms.py
from django import forms
from django.contrib.comments.forms import CommentForm
from my_comment_app.models import CommentWithReply

class CommentFormWithReply(CommentForm):
    rName = forms.CharField(widget=forms.HiddenInput,required=False)
    rContent = forms.CharField(widget=forms.HiddenInput,required=False)
    
    def get_comment_model(self):
        # Use our custom comment model instead of the built-in one.
        return CommentWithReply

    def get_comment_create_data(self):
        # Use the data of the superclass, and add in the title field
        data = super(CommentFormWithReply,self).get_comment_create_data()
        data['rName'] = self.cleaned_data['rName']
        data['rContent'] = self.cleaned_data['rContent']
        return data
    

1/gravatar/views.py
# Create your views here.

1/press/views.py
# Create your views here.
#-*- coding: UTF-8 -*-
from press.models import Press,Tag,Category
from django.shortcuts import render_to_response
from django.core.paginator import Paginator,InvalidPage,EmptyPage,PageNotAnInteger
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext

def PageView(request,p,template_name):         #分页函数
    page_size = 10
    after_range_num = 5
    before_range_num = 4
    try:
        page = int(request.GET.get("page",1))
        if page < 1:
            page = 1
    except ValueError:
        page = 1
    paginator = Paginator(p,page_size)      #分页对象
    try:
        pressList = paginator.page(page)
    except(EmptyPage,InvalidPage,PageNotAnInteger):
        pressList = paginator.page(1)
    if page >= after_range_num:
        page_range = paginator.page_range[page-after_range_num:page+before_range_num]
    else:
        page_range = paginator.page_range[0:int(page)+before_range_num]
    return render_to_response(template_name,{"p":p,"pressList":pressList,
                                           "page_range":page_range,})

def HomeView(request):
    homePress = Press.objects.all()
    template_name = 'home.html'
    return PageView(request,homePress,template_name)

def TagView(request,id):
    cate_name = Category.objects.get(id=id)
    atricles = Press.objects.filter(category=cate_name)
    return render_to_response("category.html",{"articles":atricles,"cate_name":cate_name})
    
def CategoryView(request):
    if request.GET:
        cid = int(request.GET['c'])
    else:
        cid = None
    category = Category.objects.all()
    return render_to_response("category.html",{"category":category,"cid":cid})

def ArticleView(request,id):
    next = request.path
    article = Press.objects.get(id=id)
    return render_to_response("article.html",{"article":article,"next":next},context_instance=RequestContext(request))

def ArchiveView(request):
    archivePress = Press.objects.all()
    return render_to_response('archive.html',{"presses":archivePress})
    

1/templates/archive.html
{% extends "base.html" %}

{% block content %}
	{% for press in presses %}
		
	{% endfor %}
{% endblock %}

1/templates/article.html
{% extends "base.html" %}

{% load comments %}


{% block title %}
	{{ article.title }} | CodeBlock
{% endblock %}

{% block header %}
{% load staticfiles %}
	<script src="{% static 'site/js/comment.js' %}"></script>
{% endblock %}

{% block content %}
<div class="container">
	<div class="row atricle">
		<div class="span8">
			<h1 class="text-center">{{article.title}}</h1>
			<p>{{article.content|safe}}</p>
		</div>
	</div>
	<div class="row">
		<div class="border span8">
			{% get_comment_count for article as comment_count %}
			<p class="padding">《{{article.title}}》共有<strong>{{comment_count}}</strong>条评论</p>
		</div>
	</div>
	{% render_comment_list for article %}
	<div class="row">
		<h4 id="reply_anchor" class="span6">你的回应</h4>
	</div>
	<div class="row">
		<div class="span6" id="replycontent">
		</div>
	</div>
	<div class="row">
		<div class="span6" id="comment_form">
		{% render_comment_form for article %}
		</div>
	</div>
</div>
{% endblock %}

1/templates/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta name=”description” content="CodeBlock精选国外有关编程的博客文章翻译">
		<meta name=”keyword” content="编程,IT,英文翻译,博客">
        <title> {% block title %}{% endblock %}</title>
        {% load staticfiles %}
		<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
        <link href="http://lib.sinaapp.com/js/bootstrap/2.3.1/css/bootstrap.min.css" rel="stylesheet">
		<link href="http://lib.sinaapp.com/js/bootstrap/2.3.1/css/bootstrap-responsive.css" rel="stylesheet">
		<link href="{% static 'site/site.css' %}" rel="stylesheet" />
        <script src="http://lib.sinaapp.com/js/jquery/2.0.2/jquery-2.0.2.min.js">
        </script>
        <script src="http://lib.sinaapp.com/js/bootstrap/2.3.1/js/bootstrap.min.js">
        </script>
		<script src="{% static 'site/js/site.js' %}"></script>
        {% block header %}{% endblock %}
    </head>
    <body>
    	<div id="wrap" class="container">
    			<div class="row">
                    <div class="span8">
    				<h2><a href="/">CodeBlock</a></h2>
                    </div>
    			</div>
            	<div class="row">
                <div class="span8">
                    <ul class="nav nav-tabs">
                        <li>
                            <a href="/">首页</a>
                        </li>
                        <li>
                            <a href="/category/">分类</a>
                        </li>
                        <li>
                            <a href="/archive/">归档</a>
                        </li>
                        <li>
                            <a href="/feed/">RSS订阅</a>
                        </li>
                        <!--
                        <li>
                        <a href="#">新浪微薄</a>
                        </li>
                        <li>
                        <a href="#">写信给我</a>
                        </li>
                        <li>
                        <a href="#">关于本站</a>
                        </li>
                        -->
                    </ul>
                </div>
            </div>
			{% block content %}
			{% endblock %}
			{% block pagination %}
			{% endblock %}
			<div id="push"></div>
			</div>
			<div id="footer" class="container">
	            <div class="row">
	                <div class="span3 muted footerborder">
	                	<p>本网站以翻译国外有关编程方面的文章为主，由本人vstorm维护</p>
	                </div>
	                <div class="span2 muted footerborder">
	                	<p>本站为
							<a href="http://www.gnu.org/licenses/gpl.html">GPL</a>
							开源网站,源码地址：<a href="https://github.com/vstorm/CodeBlock">GitHub</a></p>
	                </div>
	                <div class="span3 muted">
	                	<p>本站运行在新浪提供的
						<a href="http://sae.sina.com.cn/?m=front">SAE</a>
						上</p>
	                </div>
	            </div>
			</div>
    </body>
</html>

1/templates/cate.html
{% extends "base.html" %}

{% block content %}
<div class="row">
	{% for c in cate %}
		<div class="span1">
			<a href="#{{c.cname_en}}">{{c.cname}}</a>
		</div>
	{% endfor %}
</div>
<div class="row">
	{% for c in cate %}
	<a name="#{{c.cname_en}}">{{c.cname}}</a>
	<div>
		
	</div>
	{% endfor %}
</div>
{% endblock %}

1/templates/category.html
{% extends "base.html" %}

{% block title %}
	分类 ｜ CodeBlock
{% endblock %}

{% load comments %}
{% block content %}
<div class="row">
	<div class="span5">
    <div class="tabbable tabs-left">
        <!-- Only required for left/right tabs -->
        <ul class="nav nav-tabs">
            {% for c in category %}
        	<li 
				{%if cid %}
					{% ifequal cid c.id %}
						class = "active"
					{% endifequal %}
				{% else %}
					{%  if forloop.first %}
						class  = "active"
					{% endif %}
				{% endif %}>
				<a href="#{{c.cname_en}}"  data-toggle="tab">
            	{{c}}({{c.press_set.count}})
            	</a>
        	</li>
        	{% endfor %}
        </ul>
        <div class="tab-content">
            {% for c in category %}
            <div class="tab-pane {%  if forloop.first %}active{% endif %}" id="{{c.cname_en}}">
    		{% for article in c.press_set.all %}
			{% get_comment_count for article as comment_count %}
			<p class="text-center">
				<a href="/{{article.id}}">{{article.title}}</a>
				<span>({{comment_count}})</span>
			</p>
			{% endfor %}
            </div>
			{% endfor %}
        </div>
    </div>
    </div>
</div>
{% endblock %}

1/templates/comments/form.html
{% load comments i18n %}

<form action="{% comment_form_target %}" method="post">
  {% csrf_token %}
  {% if next %}<div><input type="hidden" name="next" value="{{ next }}" /></div>{% endif %}
  {% for field in form %}
    {% if field.is_hidden %}
      <div>{{ field }}</div>
    {% else %}
      {% if field.errors %}{{ field.errors }}{% endif %}
      <p
        {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
          <label>
          	{% ifequal field.name "url" %}URL(可选填) <span class="{{field.name}} text-error"></span>{% endifequal %}
			{% ifequal field.name "name" %}名称(＊必填)<span class="{{field.name}} text-error"></span>{% endifequal %}
			{% ifequal field.name "email" %}邮箱(＊必填)<span class="{{field.name}} text-error"></span>{% endifequal %}
			{% ifequal field.name "comment" %}评论(＊必填)<span class="{{field.name}} text-error"></span>{% endifequal %}
		  </label>
		  {{ field }}
      </p>
    {% endif %}
  {% endfor %}
  <p class="submit">
     <input type="submit" name="post" class="submit-post btn btn-primary" value="发表评论" />
  </p>
</form>

1/templates/comments/list.html
{%load gravatar%}
<div id="comments">
    {% for comment in comment_list %}
    <div id="c{{comment.id}}">
        <p class="text-left">
            <a href="#"><img src="{% gravatar_url comment.user_email %}"></a>
        </p>
        <p class="text-left" id="cname{{ comment.id }}">
            <a href="{{comment.url}}">{{comment.name}}</a>
        </p>
    </div>
    <div class="row">
        <div class="span6">
            {% if comment.rContent and comment.rName %}
            <blockquote>
                <p class="muted">
                	<font size="3px">
                    {{comment.rContent}}
					</font>
                </p>
                <small>
                    {{comment.rName}}
                </small>
            </blockquote>
            {% endif %}
            <p class="text-left" id="ccomment{{comment.id}}">
                {{comment.comment}}
            </p>
            <p class="muted">
                {{comment.submit_date|date:"Y年n月j日,G时i分"}}
            </p>
            <p>
                <a class="label label-info reply" href="#replycontent" name="{{comment.id}}">回复</a>
            </p>
        </div>
    </div>
    {% endfor %}
</div>

1/templates/home.html
{% extends "base.html" %}
{% load comments %}
{% block title %}
首页 ｜ CodeBlock
{% endblock %}

{% block content %}
{{ block.super }}


<div class="row">
	<div class="span8">
    <ul class="thumbnails row">
        {% for press in pressList.object_list %}
        <li class="span4">
            <div class="thumbnail">
                <a href="{{press.id}}"><img src="{{ press.cover }}" alt=""></a><a href="{{press.id}}"><h3 class="text-center">{{press.title}}</h3></a>
                <p class="text-left">
                    <strong>
                    {{press.introduce}}
                    </strong>
                </p>
				<p class="muted">
					{% get_comment_count for press as comment_count %}
					<span><a href="category/?c={{press.category.id}}">{{press.category}}</a></span>
					<span class="pull-right">{{comment_count}}条评论</span>
				</p>
            </div>
        </li>
        {% endfor %}
    </ul>
	</div>
</div>
{% endblock %}
{% block pagination %}
{% if pressList.number > 1 %}
	<div class="row">
                <div class="span12">
                    <div class="pagination pagination-centered pagination-large">
                        <ul>
                            {% if pressList.has_previous %}
                            <li>
                                <a href="?page={{ pressList.previous_page_number }}" title="pre">上一页</a>
                            </li>
                            {% else %}
                            <li class="disabled">
                                <span>上一页</span>
                            </li>
                            {% endif %}
                            {% for p in page_range %}
                            {% if p == pressList.number %}
                            <li class="active">
                                <span>{{p}}</span>
                            </li>
                            {% else %}
                            <li>
                                <a href="?page={{p}}" title="page {{p}}">{{p}}</a>
                            </li>
                            {% endif %}
                            {% endfor %}
                            {% if pressList.has_next %}
                            <li>
                                <a href="?page={{ pressList.next_page_number }}" title="next">下一页</a>
                            </li>
                            {% else %}
                            <li class="disabled">
                                <span>下一页</span>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
{% endif %}
{% endblock %}

1/templates/press/press_archive.html
{% extends "base.html" %}

{% block title %}
	归档 ｜ CodeBlock
{% endblock %}

{% load comments %}
{% block content %}
<div class="row">
	<div class="span5 offset2">
		<ul class="unstyled">
		    {% for article in latest %}
			{% get_comment_count for article as comment_count %}
		        <li>
		        	<a href="/{{article.id}}">
		        		{{ article.date_pub|date:"Y年n月j日" }}: {{ article.title }}
					</a>
					<span>({{comment_count}})</span>
				</li>
		    {% endfor %}
		</ul>
	</div>
</div>
{% endblock %}